### ISSUE TITLE
Upgrade from javax to jakarta

### ISSUE THREAD

**Issue by audunmeltzer** [digipost/signature-api-client-java#291]
Is there a timeline for upgrading from javax to jakarta?

**Comment by runeflobakk** [comment]
Sorry for the late reply.
Version [7.0-RC8](https://github.com/digipost/signature-api-client-java/pull/282), released March 16, is compatible with jakarta, and we are using it ourselves in a Spring Boot 3 application. Are you able to try the release candidate to see if it works for you? A 7.0 final release should not be far down the road.

**Comment by audunmeltzer** [comment]
Thanks for update on this :+1: 

Is it safe to use in production?
Is there a migration guide from version 6.1.1, or documented configuration of client?

When i upgraded to version 7.0-RC8 i still have reference to OldJaxb2ContextFactory, which implements javax.xml.bind.JAXBContextFactory

**Comment by runeflobakk** [comment]
Yes, I should have been more specific on that matter.
We have not migrated the JAXB-stuff to jakarta, but we have carefully selected the JAXB-dependencies to not "crash" with the equivalent jakarta-dependencies, and these are fully able to exist alongside each other. It is just another library, so to speak.

The preferred way to depend on this library is to declare _dependency management_ on this [BOM](https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#bill-of-materials-bom-poms):
```xml
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>no.digipost.signature</groupId>
                <artifactId>signature-api-client-bom</artifactId>
                <version>7.0-RC8</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
      ...
```

As well as a direct dependency to the library itself (with no version, as it is defined in the BOM above):
```xml
        <dependency>
            <groupId>no.digipost.signature</groupId>
            <artifactId>signature-api-client-java</artifactId>
        </dependency>
```

More details about javax and jakarta JAXB coexisting can be found here:
https://github.com/digipost/jaxb-resolver-com.sun.xml.bind 
The short explanation is that by carefully choosing the old javax JAXB dependencies, they happily exist alongside any new jakarta dependencies, and they are not even aware of each other, just as any unrelated libraries do not interfere with each other. The `OldJaxb2ContextFactory` you see is a sign that this mechanism is active and working as intended.

We have used this in production since March for public facing applications, and it is working as intended.

We have at this point not prepared a migration doc, but it should not be more compliacted than to fix any compilation errors appearing when upgrading. The concepts should be the same, but the API of the library may be changed here and there. If you have any questions about anything you encounter when upgrading, feel free to ask them in this issue, or even create a new issue specific for upgrading from v6 to v7.

I will do a small review of the state of the library, and do a final 7.0 release... let's say very soon :)

**Comment by audunmeltzer** [comment]
Great!

I managed to successfully sign a document i DIFIQA environment, when i used pom import. 

Thank you for update an details on dependency configuration :+1:

**Comment by runeflobakk** [comment]
Glad it worked out!

Since I had already started writing this, I am just including it here for reference.

Re configuration, this should be sufficient:

1. read your integration's enterprise certificate into a `KeyStoreConfig`:

```java
KeyStoreConfig keyStoreConfig;
try (InputStream certificateStream = // resolve certificate InputStream) {
    keyStoreConfig = KeyStoreConfig.fromOrganizationCertificate(certificateStream, certificatePassword);
} catch (IOException e) {
    throw new UncheckedIOException(e);
}
var keyStoreConfig = KeyStoreConfig.fromOrganizationCertificate(certificateInputStream, certificatePassword);
```

2. build your `ClientConfiguration`:
```java
var serviceEnvironment = // resolve the environment, e.g. ServiceEnvironment.STAGING
var clientConfiguration = ClientConfiguration.builder(keyStoreConfig)
            .serviceEnvironment(serviceEnvironment)
            .defaultSender(new Sender("987654321")) // if you typically only send from a specific Sender
            .build();
```

There are options in `ClientConfiguration.Builder` for tweaking timeouts of the internal HTTP client (Apache Http Client v5 for the time being), if needed. Prefer the methods named `timeouts(..)` and `timeoutsForDocumentDownloads(..)`, which are used like this:
```java
ClientConfiguration.builder(keyStoreConfig)
    .timeouts(t -> t
                .connectTimeout(Duration)
                .socketTimeout(Duration)
                .responseArrivalTimeout(Duration)))
```

The default values for timeouts should work without needing any tweaking, but if you still need to change any timeouts, we would very much like to hear about your use-case and rationale, to maybe improve any defaults provided by the library.

Configuring the Apache HTTP client directly is provided through the `.apacheHttpClient(a -> a.configureStuff(...))`, but this should be regarded as a non-supported API as it exposes the underlying HTTP client. Again, should you need to use this configuration facility, we would like to hear about it, to consider if we should support the configuration case directly in our library API.

**Comment by audunmeltzer** [comment]
I had to increase timeout for document downloads. We got this exception with default timeout

`Caused by: org.apache.hc.core5.http.ConnectionRequestTimeoutException: Timeout deadline: 10000 MILLISECONDS, actual: 10000 MILLISECONDS
	at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.acquireEndpoint(InternalExecRuntime.java:120)`
	
Solved it with override timeouts. It will be configurable by environment, but at first we will increase from 10s to 60s
`
.timeoutsForDocumentDownloads(t -> t
                        .connectTimeout(clientConfigurationProperties.connectionTimeout())
                        .socketTimeout(clientConfigurationProperties.socketTimeout())
                        .connectionRequestTimeout(clientConfigurationProperties.connectionRequestTimeout())
                        .responseArrivalTimeout(clientConfigurationProperties.responseArrivalTimeout()))

**Comment by audunmeltzer** [comment]
At first it seemed to solve our connection problem. But after increase connection timeout, we ended up with same exception, with new values

`Caused by: org.apache.hc.core5.http.ConnectionRequestTimeoutException: Timeout deadline: 60000 MILLISECONDS, actual: 60000 MILLISECONDS`

**Comment by audunmeltzer** [comment]
Timeouts was a wrong path from our side.

The connection pool reached its limit in production after 2 signing requests. We did manage to reproduce this i test. 

Further investigation shows that we did not close the response we received from getXAdES and getPAdES, which held connection live in connection pool. This might have been handled differently in version 6.1.1 of signing client, and might have hidden our badly response handling. 

We will soon release a new version and deploy RC8 version to prod with better response handling. I hope this solves our issue in production with RC8.

**Comment by runeflobakk** [comment]
Ah yes, I have seen another instance of this problem before with someone else's integration. I guess the new Apache HTTP client may be a bit more "sensitive" for missing resource managing. We didn't hear anything more after they sorted out the proper closing of the InputStream, so I think everything works as it should.

Thanks for the heads-up. I think I will include some more context in the thrown exception from the client if it encounters a `ConnectionRequestTimeoutException`, hinting to maybe not appropriately closing the streamed content. And try to document the importance of properly managing and closing the `InputStream` when fetching document content.

**Comment by runeflobakk** [comment]
@audunmeltzer I have prepared PR #300 to give some hints about possible missing resource management when a `ConnectionRequestTimeoutException` is thrown. Feel free to comment on the PR, if you have anything to add! 😃
